// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6ZM9Qkru5iQqlv7067SSnO5abYlq2erc',
    appId: '1:707384928949:web:d53246db4a2cd8cbd5acfc',
    messagingSenderId: '707384928949',
    projectId: 'todoapp-c9dfb',
    authDomain: 'todoapp-c9dfb.firebaseapp.com',
    storageBucket: 'todoapp-c9dfb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGkK3ZqwzSRMktPs9UfEQfL0pDuWUJ91g',
    appId: '1:707384928949:android:4fa85e2d36fb3fd9d5acfc',
    messagingSenderId: '707384928949',
    projectId: 'todoapp-c9dfb',
    storageBucket: 'todoapp-c9dfb.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6ZM9Qkru5iQqlv7067SSnO5abYlq2erc',
    appId: '1:707384928949:web:5e84eecfce987c4dd5acfc',
    messagingSenderId: '707384928949',
    projectId: 'todoapp-c9dfb',
    authDomain: 'todoapp-c9dfb.firebaseapp.com',
    storageBucket: 'todoapp-c9dfb.firebasestorage.app',
  );
}
